### ISSUE TITLE
Lob rock

### ISSUE THREAD

**Issue by smythp** [cbeo/hyperthings.garden#1]
I noticed that your digital garden doesn't have an RSS feed. That means, practically speaking, that I'll lose track of it. However, if I lob this rock, perhaps I will create a karmic disturbance that will bring your blog back to my attention at irregular intervals.

Incoming.

						.... ..		. .  ..
					       ..	..... .	       .  ..
..	.	 .			       ... .			 ........
						  ..			   ....
				      .					   .....
				   . . ....	  ..			    . .	 . .
.				  ..		    .				   ..
.      .       ....		 .  .	...	     .				     .
				..  .	     .	..	       .       ..	    ...
			     ......	       . .			. .	   ..
			     ...	       .		      .	  .
.      .       .  .	   ..		..			      .	  .	   .
		  ..	   .		      .	.	 .	    . .		...
			   ..	       .. .... ....... ..  . ..		       ....
			    ..			       ..			..
				   ............................................	 .
		. ....		................ .. ............................
.      ..... ...
.

		   ...
	       .....
       .....
...... .
.

**Comment by smythp** [comment]
I made the rock in Emacs, and I'm mostly blind, so it's not very good. Just in case you would think I was proud of the rock.

**Comment by cbeo** [comment]
It has several rss feeds !   https://hyperthings.garden/posts.html  

One for all posts, and one for each tag.

**Comment by cbeo** [comment]
Hmm. perhaps screen readers cannot find my feeds?  I wonder... what I can do. I'll install one and see if I can figure it out.

**Comment by smythp** [comment]
I found it readily enough on my phone with a proper screen reader, on the computer I did a lazy search through the source for "rss." Should have searched for "xml" as well. The fact that the feed is an image while the other links aren't tripped me up a little. Got you in my feed now, along with some of your recommendations on the fellows page. Thanks!

**Comment by cbeo** [comment]
Excellent! thanks for bringing this to my attention and I'm sorry that you had to. I'll figure something out. Maybe I didn't put an alt text in the rss icon image... I can't remember.

Thanks again!
